### ISSUE TITLE
cant connect to proxy

### ISSUE THREAD

**Issue by parafius** [inanitynoupcase/nodepay#1]
endless attempts to connect to proxy, with proxy everything is ok

**Comment by inanitynoupcase** [comment]
Did u mean "retry" ? It's normal bro, just let the tool running

**Comment by BaoTrNG** [comment]
> endless attempts to connect to proxy, with proxy everything is ok

I Need image for further debugging, for the best result please use private static residental ipv4

**Comment by parafius** [comment]
> > endless attempts to connect to proxy, with proxy everything is ok
> 
> I Need image for further debugging, for the best result please use private static residental ipv4

I am using static http proxies, can't provide a screenshot of the error as the trial version has ended but the error was with multiple attempts to connect to the proxy

**Comment by inanitynoupcase** [comment]
> > > endless attempts to connect to proxy, with proxy everything is ok
> > 
> > 
> > I Need image for further debugging, for the best result please use private static residental ipv4
> 
> I am using static http proxies, can't provide a screenshot of the error as the trial version has ended but the error was with multiple attempts to connect to the proxy

Contact me in telegram and i will give you one more trial to see what error u face
